# Site-level variables
title: Varada's GitHub
# description: Sharing documents and supporting materials for my publications.
# author: Varada

# Jekyll theme configuration
# Use one of the official Jekyll themes
theme: minima

plugins:
  - jekyll-feed

collections:
  pages:
    output: true
  
# Exclude these pages from the sitemap
exclude:
  - "/_config/"
  - "/.github/"
  - "/md/"
