# Site-level variables
title: Varada's GitHub
description: Share documents and supporting materials for my publications.
author: Varada

# Jekyll theme configuration
# Use one of the official Jekyll themes
theme: minima

# Or a remote theme from a GitHub repository
# remote_theme: jekyll/minima
