name: Build and deploy Jekyll site (with plugins)

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
      - name: Install bundler and deps
        run: |
          gem install bundler
          bundle config set path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Build the site
        run: bundle exec jekyll build --destination ./_site
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          # You can set user_name and user_email if you want a custom commit author
