name: List Markdown Files

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 23 * * *" # Runs daily at 11pm UTC

jobs:
  list-md-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find all .md files and update md.txt
        run: |
          mkdir -p .github/workflow
          find . -type f -name "*.md" | sort > .github/workflow/md.txt

      - name: Commit and push md.txt
        run: |
          git config --local user.name "ivarada"
          git config --local user.email "varada@"
          git add .github/workflow/md.txt
          git commit -m "Update md.txt with list of all Markdown files" || echo "No changes to commit"
          git push
