name: List Markdown Files

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 23 * * *" # Runs daily at 11pm UTC

jobs:
  list-md-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find all .md files and update md.txt
        run: |
          mkdir -p _config
          echo "MD HTML File List -- START" > _config/md-html-files-list.txt
          echo "MD HTML File List" >> _config/md-html-files-list.txt
          echo "---MD---" >> _config/md-html-files-list.txt
          find . -type f -name "*.md" | sort >> _config/md-html-files-list.txt
          echo "---HTML---" >> _config/md-html-files-list.txt
          find . -type f -name "*.html" | sort >> _config/md-html-files-list.txt
          echo "MD HTML File List -- END" >> _config/md-html-files-list.txt

      - name: Commit and push md.txt
        run: |
          git config --local user.name "ivarada"
          git config --local user.email "varada@"
          git add _config/md-html-files-list.txt
          git commit -m "Update md.txt with list of all Markdown files" || echo "No changes to commit"
          git push
