name: Rename Markdown Files

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 23 * * *"

jobs:
  rename-md-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rename .md files to lowercase and replace spaces
        run: |
          find . -type f -name "*.md" ! -iname "LICENSE.md" ! -iname "README.md" | while read file; do
            dir=$(dirname "$file")
            base=$(basename "$file")
            newbase=$(echo "$base" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
            if [ "$base" != "$newbase" ]; then
              git mv "$file" "$dir/$newbase"
            fi
          done

      - name: Commit changes
        run: |
          git config --local user.name "ivarada"
          git config --local user.email "varada@"
          git commit -am "Rename .md files to lowercase and replace spaces with hyphens" || echo "No changes to commit"
          git push
